name: Workflow Run

permissions:
    actions: write
    checks: write
    contents: write
    deployments: write
    pull-requests: write
    statuses: write

on:
    workflow_run:
        workflows: ['Pull Request']
        types:
            - completed
jobs:
    build_to_cloudflare_pages:
        runs-on: Ubuntu-latest
        env: 
            TEMP_2: ${{ secrets.TEMP_2 }}
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}
            - name: Download artifact
              run: |
                bash test.sh
